### ISSUE TITLE
virtual keyboard is not  displayed while clicking on its icon on sddm page

### ISSUE THREAD

**Issue by CatShadow44** [L4ki/Relax-Plasma-Themes#1]
![image](https://user-images.githubusercontent.com/85686242/154335428-017394cc-588f-44ae-a97f-aa3a015abd7e.png)

**Comment by CatShadow44** [comment]
Hi, 
Can you please help me, 
when i'm on login screen with relax theme (dark version), 
nothing appends when i click on the virtual keyboard button

Manjaro (up to date) kde version 
relax-sddm theme

**Comment by L4ki** [comment]
Hi CatShadow44,

I checked and everything is fine. I also tried Virtual Machine and everything is fine.

Screenshot: https://ibb.co/nbLQyKV

I don't know why he doesn't work on your computer. 

See here: https://forum.manjaro.org/t/virtual-keyboard-not-available-on-login-screen/97150/2
