### ISSUE TITLE
Possible KDE Plasma 5.24 bug affecting title bar

### ISSUE THREAD

**Issue by Sadi58** [L4ki/Relax-Plasma-Themes#2]
I think KDE Plasma 5.24 has arrived with a bug somewhere that's causing a flickering effect on the title bar when using any Aurorae theme with transparency. I just wanted to check this with you, and perhaps you know better where the bug might be, so that it can be reported better. I see the stripe at the top on and off, and it often appears similarly on the right and left edges of the title bar as well. 
![Screenshot_2022-03-23_12-35-37](https://user-images.githubusercontent.com/6375934/159671554-24eb5a3e-e385-4775-9c66-8389c1c9a393.jpg)

**Comment by L4ki** [comment]
Hi Sadi,

I am using openSUSE Tumbleveed, Plasma 5.24.3

Aurorae Theme "Relax-Blur-Light-Aurorae", with me, looks like this: 

[![Screenshot-20220323-121600.png](https://i.postimg.cc/W3t6Cb2X/Screenshot-20220323-121600.png)](https://postimg.cc/1nhqNSVq)

I didn't notice flickering effect. 

P.S.

What's new in Istanbul? Earlier as I worked in the transport company, once a month I was the guest of Istanbul. Old good times.  (Between 1987-2000. years)

**Comment by Sadi58** [comment]
Hi, I'm using KDE neon. It seems this happens when the window is touching the top panel, latte dock to be more precise, and mostly triggered when the mouse is moved over it. I'll also try with no Latte Dock, with KDE's own top panel etc. and report back. Perhaps latte dock is the culprit. Thanks.
![Screenshot_2022-03-23_17-45-24](https://user-images.githubusercontent.com/6375934/159726761-e47b0783-d30a-4472-ad62-3b19e42c69e9.jpg)
P.S. Istanbul changed a lot in the last 20 years, mostly for the better IMHO ;-)

**Comment by Sadi58** [comment]
Yes, it seems there's some weird thing going on between my latte dock top panel (3 floating docks actually) transparency, and the transparency in the title bar, because there is no such thing if either one is withdrawn from the equation. Since title bar transparency is a very simple setting, the bug must be in latte dock?
I'll keep my windows off that top panel ;-)

**Comment by Sadi58** [comment]
Weird; I reduced latte dock opacity from 10% to 0% (i.e. 100% transparency) , and the problem is gone.
