### ISSUE TITLE
Not an issue, a request

### ISSUE THREAD

**Issue by tdtooke** [L4ki/Relax-Plasma-Themes#3]
I'm putting together a version of this that is TokyoNight.  Another guy made a color scheme, I made a konsole theme.  Really the only difference between TokyoNight and this theme that I haven't addressed is the windows decorations.  I know I could edit the svg's myself.  Probably do it with just bucket fill on GIMP but the thing is there are subtle differences in shading in that and I have zero artistic judgement when it comes to that sort of thing.  So I was going to ask if you could do windows decorations that would match the already existing TokyoNight GTK theme.  Please feel free to say no, but it'd be really awesome if you did that.

**Comment by L4ki** [comment]
Hi tdtooke, 

My suggestion is to contact the author of GTK Theme "Tokyo Night", that is Mr. fkorpsvart (Fausto-Korpsvart). 

Greetings,

**Comment by tdtooke** [comment]
I did leave a message for him.  I finally did take a stab at it and as far as I can tell it's virtually indistinguishable from what I see from the gtk4 theme.  I ended up using inkscape to modify the svgs in your aurorae.  One thing, how do you set a color by hand on that????  I could figure out how to select different pallettes but I never figured out how to just set the rgb or the #feetc... for a custom color.  What app do you use to edit svgs?  I was disappointed that gimp wouldn't let me save it as an svg.  I actually sortof know what I'm doing in that app.  If I get this into a state fit to be shared can I include most of your theme in it.  I find that what I want pretty much is what you've done here, just with a different color pallette.  Very excellent theme by the way.  This and pax are among my favorites.

Edit:  Sorry, nevermind, just figured it out.

**Comment by L4ki** [comment]
Hi tdtooke,

You can freely use my Themes and customize them as you wish. 

Otherwise, I use the Inkscape application.
