### ISSUE TITLE
Highlighted icons in Icons-only Task Manager shrink a lot

### ISSUE THREAD

**Issue by tnordenmark** [L4ki/Relax-Plasma-Themes#4]
First of all, great work on the theme. It looks awesome!

However I have an issue with the Icons-only task manager in Plasma which I think is because of this theme. Whenever an icon is highlighted it shrinks all the icons to about half the size because the highlight region is too big. See screenshots below.

Icons small:
![icons shrunk](https://github.com/L4ki/Relax-Plasma-Themes/assets/3521892/0b66120e-a11e-4831-82c4-e2a332c4dcf9)
<br>

Icons normal size:
![icons normal](https://github.com/L4ki/Relax-Plasma-Themes/assets/3521892/f02f33e9-8fcc-4319-b977-7aca904b3699)

~~It seems it only happens if the icons (and panel) are smaller than 48 px.~~
It happens no matter the icon size.          
<br>

![image](https://github.com/L4ki/Relax-Plasma-Themes/assets/3521892/0e85896e-1736-46e2-b461-2c7b9ce73873)

**Comment by L4ki** [comment]
Hi Thomas,

You're right. I will update as soon as possible. Greeting,

**Comment by L4ki** [comment]
Hi Thomas,

I just released an update to the Plasma Theme "Relax-Plasma": https://www.pling.com/p/1687614/ 

I think it's better now. Please let me know your impressions.

**Comment by tnordenmark** [comment]
Hello, I was away during the weekend but I have now tested the new version and it is indeed working. Thanks for the quick response!
<br>

![icons working](https://github.com/L4ki/Relax-Plasma-Themes/assets/3521892/21f2db35-9cb5-4eae-807b-8991f987c181)

**Comment by L4ki** [comment]
Hi Thomas.

But this screenshot you posted is not from the Plasma Theme ""Relax-Plasma".

This is what it should look like: 

https://postimg.cc/R3VwLRhF

**Comment by tnordenmark** [comment]
For some reason the Relax-Global theme was installed in the wrong location, once I put it where it should be things turned transparent. Overall transparency has been a bit inconsistent on Wayland with Intel iGPU. At least in Fedora 38 as I have 2 machines where the plasma panel does what it likes no matter if you set it to Adaptive, Opague or Translucent.
Also, I used different icons in the screenshots just to see if the task manager behaved differently.

The ocs-url helper app installed the Relax-Global theme in `/home/user/.local/share/plasma/desktoptheme/` and not `/home/user/.local/share/plasma/look-and-feel/`

However the task manager is working and that's what matters :smiley: 
<br>
![icons working](https://github.com/L4ki/Relax-Plasma-Themes/assets/3521892/092dd6aa-b9bd-451f-84d7-b73e37d918cf)

**Comment by L4ki** [comment]
I'm glad he's okay now.

Greeting,
